### ISSUE TITLE
Not working on 6.11.1

### ISSUE THREAD

**Issue by mathewtonyt** [idanto/node-metrics#21]
getting this error, while installing on v6.11.1

`"stack": ["Error: Cannot find module '../build/Release/eventLoopStats'", "    at Function.Module._resolveFilename (module.js:469:15)", "    at Function.Module._load (module.js:417:25)", "    at Module.require (module.js:497:17)", "    at require (internal/module.js:20:19)", "    at Object.<anonymous> (/opt/socket.io-chat/node_modules/event-loop-stats/src/eventLoopStats.js:1:84)", "    at Module._compile (module.js:570:32)", "    at Object.Module._extensions..js (module.js:579:10)", "    at Module.load (module.js:487:32)", "    at tryModuleLoad (module.js:446:12)",
"    at Function.Module._load (module.js:438:3)", "    at Module.require (module.js:497:17)", "    at require (internal/module.js:20:19)", "    at Object.<anonymous> (/opt/socket.io-chat/node_modules/express-node-metrics/src/metrics.js:5:22)", "    at Module._compile (module.js:570:32)", "    at Object.Module._extensions..js (module.js:579:10)", "    at Module.load (module.js:487:32)"],
    "level": "error",
    "message": "uncaughtException: Cannot find module '../build/Release/eventLoopStats'",
    "timestamp": "2017-09-12T04:57:22.470Z"`

on host - Red Hat Enterprise Linux Server release 6.6

**Comment by idanto** [comment]
Thank for the issue @mathewtonyt.
Can you please share the output of the `npm install` command?

Please also make sure you have installed `g++-4.8` (GCC) in your server/workstation.

**Comment by mathewtonyt** [comment]
No we use - gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) , so what are my options ? is this a node.js/v8 dependency

**Comment by idanto** [comment]
nope, it's dependency for one of the packages.
I have to check what I can do, I think that package can be removed because new features that added to node core in v6 and v8.

I will get back to you with that
